title: "T. H. Fahim"
description: "Work & Projects"
url: "https://thfahim-xyz.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /posts/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap